from enum import Enum

class Project_Enum(Enum):
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"    
    FILE_VALIDATE_SUCCESSFULLY = "FILE_VALIDATE_SUCCESSFULLY"
    FILE_UPLOADED_FAILED = "FILE_UPLOADED_FAILED"
    FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    File_NOT_FOUND_OR_COULD_NOT_BE_LOADED = "File_NOT_FOUND_OR_COULD_NOT_BE_LOADED"
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    FILE_COULD_NOT_BE_SPLIT = "FILE_COULD_NOT_BE_SPLIT"
    NO_FILE_EXIST="NO_FILE_EXIST"
   


