from enum import Enum

class Project_Enum(Enum):
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"    
    FILE_VALIDATE_SUCCESSFULLY = "FILE_VALIDATE_SUCCESSFULLY"