from enum import Enum

#this class store any constant string to manage it or change from it in easy way 

class Project_Enum(Enum):
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"    
    FILE_VALIDATE_SUCCESSFULLY = "FILE_VALIDATE_SUCCESSFULLY"
    FILE_UPLOADED_FAILED = "FILE_UPLOADED_FAILED"
    FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    File_NOT_FOUND_OR_COULD_NOT_BE_LOADED = "File_NOT_FOUND_OR_COULD_NOT_BE_LOADED"
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
    FILE_COULD_NOT_BE_SPLIT = "FILE_COULD_NOT_BE_SPLIT"
    NO_FILE_EXIST="NO_FILE_EXIST"
    PROJECT_NOT_FOUND_ERROR="PROJECT_NOT_FOUND_ERROR"
    INSERT_INTO_VECTOR_DB_ERROR="INSERT_INTO_VECTOR_DB_ERROR"
    INSERT_INTO_VECTOR_DB_SUCESS="INSERT_INTO_VECTOR_DB_SUCESS"
    PROJECT_NOT_FOUND_ERROR="PROJECT_NOT_FOUND_ERROR"
    VECTOR_DB_COLLECTION_RETRIEVED="VECTOR_DB_COLLECTION_RETRIEVED"
    PROJECT_NOT_FOUND_ERROR="PROJECT_NOT_FOUND_ERROR"
    VECTOR_DB_SEACH_ERROR="VECTOR_DB_SEACH_ERROR"
    VECTOR_DB_SEACH_SUCCESS="VECTOR_DB_SEACH_SUCCESS"


